name: Deploy to Cloud Run
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Authenticate
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        
    - name: Setup GCloud
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        
    # REMOVED API ENABLEMENT STEP
    # APIs are now manually enabled
        
    - name: Deploy
      run: |
        gcloud run deploy diabetes-mvp \
          --region=europe-west1 \
          --allow-unauthenticated \
          --source .
