name: Deploy to Cloud Run
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    # ADD THESE 2 CRITICAL STEPS
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      
    # MODIFIED DEPLOY COMMAND
    - name: Deploy to Cloud Run
      run: |
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        gcloud run deploy diabetes-mvp \
          --platform managed \
          --region europe-west1 \
          --allow-unauthenticated \
          --source .
